language: csharp
mono: none
dotnet: 1.0.0-preview3-004056
solution: stashbox.extensions.dependencyinjection.sln
dist: trusty
sudo: required

os:
  - linux
  - osx

osx_image: xcode7.3
  
before_script:
  - dotnet restore

script:
  - dotnet test test/stashbox.extensions.dependencyinjection.specificationtests/stashbox.extensions.dependencyinjection.specificationtests.csproj -c Release -f netcoreapp1.1