version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release
  
before_build:
- dotnet restore

build_script:
- dotnet build src --configuration %CONFIGURATION% --no-dependencies
  
after_build:
- dotnet pack src --configuration %CONFIGURATION% --no-build --output artifacts --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
- dotnet test test\stashbox.extensions.dependencyinjection.specificationtests
  
artifacts:
- path: artifacts\Stashbox.*.nupkg
  name: Nuget Package

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true